version: '3'

services:
  apig:
    image: quhan/api-gateway:latest
    container_name: apig-component
    ports:
      - "1000:1000" 
    depends_on:
      - message
      - notification
      - gps
      - authms
      - user
  message:
    image: julianfernandezs/messagems:latest
    container_name: message-microservice
    ports:
      - "8000:8000"

  notification:
    image: jyarac/notification-ms:latest
    container_name: notification-microservice
    ports:
      - "3000:3000"

  gps:
    image: jyarac/gps:latest
    container_name: gps-microservice
    ports:
      - "3001:3001"

  authms:
    image: jfc12/authms:latest
    depends_on:
        - "authmsdbc"
    container_name: authms_c
    ports:
        - "7049:80"
    environment:
      ASPNETCORE_URLS: "http://+"
      ASPNETCORE_ENVIRONMENT: Development


  authmsdbc:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: authmsdbc
    ports:
        - "1433:1433"
    environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Password1!"

  user:
    image: quhan/users:latest
    container_name: user-microservice
    ports:
      - "8080:8080"


